laptop:
	sudo guix system reconfigure -L ${HOME}/git/dotfiles/guix ${HOME}/git/dotfiles/guix/noonker/system/personal-laptop.scm
home:
	guix home reconfigure /home/person/git/dotfiles/guix/noonker/home/home-configuration.scm
iso:
	guix system image -t iso9660 -L ${HOME}/git/dotfiles/guix ${HOME}/git/dotfiles/guix/noonker/system/personal-laptop.scm
