;; TidalCycles bootstrap package.
;;
;; Guix does not (yet) ship the `tidal' Haskell library nor the SuperDirt
;; SuperCollider quark.  Rather than vendoring the full Haskell dependency
;; graph through `haskell-build-system', this package propagates the three
;; pieces that *are* in Guix (ghc, cabal-install, supercollider) and ships a
;; small `tidal-bootstrap' script that the user runs once to:
;;
;;   1. `cabal install --lib tidal' into the user's cabal store, and
;;   2. print the SuperDirt quark install snippet to paste into sclang.
;;
;; After bootstrapping, `:l BootTidal.hs' in ghci (or emacs tidal-mode)
;; connects to a running SuperDirt instance.

(define-module (noonker packages tidalcycles)
  #:use-module (gnu packages audio)         ;supercollider
  #:use-module (gnu packages bash)          ;bash-minimal
  #:use-module (gnu packages haskell)       ;ghc
  #:use-module (gnu packages haskell-apps)  ;cabal-install
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix build-system trivial)
  #:export (tidalcycles))

(define-public tidalcycles
  (package
    (name "tidalcycles")
    (version "1.9.5")
    (source #f)
    (build-system trivial-build-system)
    (arguments
     (list
      #:modules '((guix build utils))
      #:builder
      #~(begin
          (use-modules (guix build utils))
          (let* ((out  (assoc-ref %outputs "out"))
                 (bin  (string-append out "/bin"))
                 (boot (string-append bin "/tidal-bootstrap")))
            (mkdir-p bin)
            (call-with-output-file boot
              (lambda (port)
                (format port "#!~a/bin/bash
# Generated by the (noonker packages tidalcycles) Guix package.
set -euo pipefail

GHC=~a/bin/ghc
CABAL=~a/bin/cabal

echo '==> cabal update'
\"$CABAL\" update

echo \"==> cabal install --lib tidal (ghc $(\\\"$GHC\\\" --numeric-version))\"
\"$CABAL\" install --lib tidal --with-compiler=\"$GHC\"

cat <<'EOF'

TidalCycles Haskell library installed into the user cabal store.

Next, install the SuperDirt SuperCollider quark.  Open scide (or sclang)
and evaluate:

  Quarks.checkForUpdates({
    Quarks.install(\"SuperDirt\");
    thisProcess.recompile;
  });

Wait for the install to finish, then in a future session start SuperDirt
with:

  SuperDirt.start;

Connect a Tidal session from emacs tidal-mode (or ghci with
:l BootTidal.hs) and you are live.
EOF
"
                        #$bash-minimal
                        #$ghc
                        #$cabal-install)))
            (chmod boot #o755)))))
    (propagated-inputs
     (list bash-minimal ghc cabal-install supercollider))
    (home-page "https://tidalcycles.org/")
    (synopsis "TidalCycles live-coding pattern language (Guix bootstrap)")
    (description
     "TidalCycles is a domain-specific language embedded in Haskell for
live-coding algorithmic patterns, typically driving SuperDirt running in
SuperCollider.  Because the @code{tidal} Haskell library and the
@code{SuperDirt} SuperCollider quark are not currently packaged for Guix,
this package propagates @code{ghc}, @code{cabal-install} and
@code{supercollider} into the user's profile and installs a
@command{tidal-bootstrap} shell script.  Run @command{tidal-bootstrap}
once after installing this package to fetch the @code{tidal} library
into your cabal store; the script also prints the sclang snippet for
installing SuperDirt.")
    (license license:gpl3+)))

tidalcycles
